name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"

    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Check dependencies
      run: make check-deps

    - name: Run tests
      run: make test

    - name: Build release
      run: make build
      env:
        CI: true

    - name: Verify binary
      run: |
        echo "Build directory contents:"
        find .build -name "macnav" -type f || true
        echo "Checking binary:"
        if [ -f .build/release/macnav ]; then
          file .build/release/macnav
        else
          echo "Binary not at expected location, searching..."
          find .build -name "macnav" -type f | head -1 | xargs file || true
        fi

  build-universal:
    name: Build Universal Binary
    runs-on: macos-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"

    - name: Build universal binary
      run: |
        swift build -c release --arch arm64
        swift build -c release --arch x86_64
        mkdir -p .build/universal
        lipo -create -output .build/universal/macnav .build/arm64-apple-macosx/release/macnav .build/x86_64-apple-macosx/release/macnav

    - name: Create app bundle
      run: |
        mkdir -p macnav.app/Contents/MacOS
        mkdir -p macnav.app/Contents/Resources
        cp .build/universal/macnav macnav.app/Contents/MacOS/macnav
        cat > macnav.app/Contents/Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
        	<key>CFBundleExecutable</key>
        	<string>macnav</string>
        	<key>CFBundleIdentifier</key>
        	<string>com.macnav.macnav</string>
        	<key>CFBundleName</key>
        	<string>macnav</string>
        	<key>CFBundleVersion</key>
        	<string>$(cat VERSION)</string>
        	<key>CFBundleShortVersionString</key>
        	<string>$(cat VERSION)</string>
        	<key>CFBundleInfoDictionaryVersion</key>
        	<string>6.0</string>
        	<key>CFBundlePackageType</key>
        	<string>APPL</string>
        	<key>LSMinimumSystemVersion</key>
        	<string>12.0</string>
        	<key>LSApplicationCategoryType</key>
        	<string>public.app-category.utilities</string>
        	<key>NSHighResolutionCapable</key>
        	<true/>
        	<key>LSUIElement</key>
        	<true/>
        </dict>
        </plist>
        EOF

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macnav-macos
        path: |
          .build/universal/macnav
          macnav.app/
        retention-days: 30